import type { Metadata } from "next";
import "./globals.css";
import request from '@/services/request'
import { IUser } from "@/types";
import { SiteHeader } from "@/components/header";
import { SiteFooter } from "@/components/footer"
import { FPSCounter } from "@/components/fps-counter"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 只能使用 NEXT_PUBLIC_ 开头的环境变量
  const data = await request.get<IUser>('/user')
  console.log(data.data.pagination)
  return (
    <html lang="en">
      <body className={` antialiased`}>
      <FPSCounter />
        <SiteHeader></SiteHeader>
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
