import type { Metadata } from "next";
import "./globals.css";
import request from '@/services/request'
import { IUser } from "@/types";
import { SiteHeader } from "@/components/header";
import { SiteFooter } from "@/components/footer"
import { FPSCounter } from "@/components/fps-counter"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await request.get<IUser>('/user')
  console.log(data.data.pagination)
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col antialiased">
        <FPSCounter />
        <SiteHeader />
        <main className="flex-1">{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}
